server:
  port: 8040
spring:
  application:
    name: user
  datasource:
    username: root
    password: oscargk707yzyz.
    url: jdbc:mysql://localhost:3306/ordersys?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.yz.pojo
